# Generated by Django 4.2.1 on 2023-06-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ladyshoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=300)),
                ('price', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Womenshoes',
        ),
    ]
