# Generated by Django 4.2.1 on 2023-06-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ladyshoes_delete_womenshoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ladyshoes',
            new_name='Products',
        ),
    ]
